/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function keys(): number;
export function test1(a: number): void;
export function send_mouse_pos(a: number, b: number): number;
export function send_key(a: number, b: number): number;
export function send_mouse(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): number;
export function get_image(): number;
export function store_value_in_wasm_memory_buffer_index_zero(a: number): void;
export function read_wasm_memory_buffer_and_return_index_one(): number;
export function get_wasm_memory_buffer_pointer(): number;
export function host(a: number, b: number, c: number, d: number): number;
export function login(a: number, b: number, c: number, d: number): number;
export function close(): number;
export function __wbg_keyboard_free(a: number): void;
export function keyboard_new(): number;
export function keyboard_press_key(a: number, b: number): number;
export function keyboard_hold_Key(a: number, b: number): number;
export function keyboard_key_combination(a: number, b: number): number;
export function __wbg_web_socket_free(a: number): void;
export function test(a: number): void;
export function web_socket_new(a: number, b: number): number;
export function web_socket_state(a: number): number;
export function web_socket_connect(a: number, b: number): number;
export function web_socket_send(a: number, b: number, c: number): void;
export function web_socket_on_message(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__ha83dd714f60d3dca(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hb702dce18469130a(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h1705e5d3354e6877(a: number, b: number, c: number, d: number): void;
